//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tms
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRuleCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessRuleCondition()
        {
            this.BusinessRuleCondition1 = new HashSet<BusinessRuleCondition>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Criteria { get; set; }
        public Nullable<int> Condition { get; set; }
        public string Value { get; set; }
        public Nullable<int> BusinessRuleID { get; set; }
        public Nullable<int> BusinessRuleConditionID { get; set; }
        public Nullable<int> BusinessRuleConditionLevel { get; set; }
    
        public virtual BusinessRule BusinessRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessRuleCondition> BusinessRuleCondition1 { get; set; }
        public virtual BusinessRuleCondition BusinessRuleCondition2 { get; set; }
    }
}
