//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tms
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityMatrixItem
    {
        public int ID { get; set; }
        public int ImpactID { get; set; }
        public int UrgencyID { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual Impact Impact { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Urgency Urgency { get; set; }
    }
}
